export const images = {
  earth: require("../../assets/images/earth.png"),
  mascotLogo: require("../../assets/images/moscot-logo.png"),
  mascotWelcome: require("../../assets/images/mascot-welcome.png"),
  mascotAuth: require("../../assets/images/mascot-auth.png"),
  treasure: require("../../assets/images/treasure.png"),
  palace: require("../../assets/images/palace.png"),
  streakFire: require("../../assets/images/streak-fire.png"),
  aiTeacherAvatar: require("../../assets/images/ai-teacher-avatar.jpg"),
  mascotCafeBanner: require("../../assets/images/mascot-cafe-banner.png"),
  cafeTableIcon: require("../../assets/images/cafe-table-icon.png"),
  mascotGreetingsBanner: require("../../assets/images/mascot-greetings-banner.png"),
  aiTeacherFoxScene: require("../../assets/images/ai-teacher-fox-scene.jpg"),
  learnerPipAvatar: require("../../assets/images/learner-pip-avatar.jpg"),
};